import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import { Header } from "@/components/header";
import "./globals.css";
import { ModalProvider } from "@/components/providers/modal-provider";
import { cn } from "@/lib/utils";

const rubik = Rubik({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(rubik.className, "flex flex-col min-h-screen relative")}
      >
        <Header />
        <div className="pt-[4rem]">{children}</div>
        <ModalProvider />
      </body>
    </html>
  );
}
