import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import { Header } from "@/components/header";
import "./globals.css";
import { ModalProvider } from "@/components/providers/modal-provider";
import { cn } from "@/lib/utils";
import { auth } from "@/auth";
import { SessionProvider } from "@/components/providers/session-provider";
import { QueryProvider } from "@/components/providers/query-provider";

const rubik = Rubik({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={cn(rubik.className, "flex flex-col min-h-screen relative")}
      >
        <SessionProvider session={session}>
          <QueryProvider>
            <Header />
            <div className="pt-[4rem] max-w-7xl mx-auto w-full">{children}</div>
            <ModalProvider />
          </QueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
